name: Run Benchmarks

on:
  workflow_dispatch:

jobs:
  benchmark:
    runs-on: ubuntu-latest

    container:
      image: sbtscala/scala-sbt:eclipse-temurin-21.0.7_6_1.11.3_3.7.1

    steps:
      - name: Install make
        run: apt-get update && apt-get install -y make

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run all benchmarks
        run: make bench_all

      - name: Upload all benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: analysis/data/
